#Configure Master and Slave Nodes

- hosts: tag_node_NameNode,tag_node_DataNode

  tasks:

  - name: Search JDK
    command: rpm -q /root/Hadoop/jdk-8u171-linux-x64.rpm
    register: jdk
    ignore_errors: yes

  - debug:
      var: jdk.stdout

  - name: Search Hadoop
    command: rpm -q /root/Hadoop/hadoop-1.2.1-1.x86_64.rpm
    register: hadoop
    ignore_errors: yes

  - debug:
      var: hadoop.stdout

  - name: Copy JDK
    copy:
      src: jdk-8u171-linux-x64.rpm
      dest: /root/Hadoop/
    when: jdk.rc != 0
  
  - name: Copy Hadoop
    copy:
      src: hadoop-1.2.1-1.x86_64.rpm
      dest: /root/Hadoop/
    when: hadoop.rc != 0

  - name: install JDK
    command: rpm -i /root/Hadoop/jdk-8u171-linux-x64.rpm
    register: jdktool
    ignore_errors: yes
    when: jdk.stdout != "jdk1.8-1.8.0_171-fcs.x86_64"

  - debug:
      var: jdktool

  - name: install Hadoop
    command: rpm -i /root/Hadoop/hadoop-1.2.1-1.x86_64.rpm --force
    register: hadooptool
    ignore_errors: yes
    when: hadoop.stdout != "hadoop-1.2.1-1.x86_64"

  - debug:
      var: hadooptool

#configure Master Node
- hosts: tag_node_NameNode
  vars:
    node: "NameNode"

  tasks:
  - name: Copy HDFS-SITE.xml file
    template:
      src: hdfs-site.xml
      dest: /etc/hadoop/

  - name: Copy CORE-SITE.xml file
    template:
      src: core-site.xml
      dest: /etc/hadoop/

  - name: Format namenode
    shell: echo Y | hadoop namenode -format
    
  - name: Start namenode
    command: hadoop-daemon.sh start namenode
        
#Configure Slave Node
- hosts: tag_node_DataNode
  vars:
    node: "DataNode"

  tasks:
  - name: Copy HDFS-SITE.xml file
    template:
      src: hdfs-site.xml
      dest: /etc/hadoop/

  - name: Copy CORE-SITE.xml file
    template:
      src: core-site.xml
      dest: /etc/hadoop/

  - name: Start datanode
    command: hadoop-daemon.sh start datanode
   


  
  






